name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gcc          # C compiler
  - gxx          # C++ compiler
  - cmake        # ✅ Add this line
  - pyyaml
  - hydra-core=1.3.2
  - numpy=1.24
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0