name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - numpy=1.24
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pyarrow=12.0.1   # Downgraded to ensure compatibility
  - cmake            # To support Arrow builds
  - libarrow=12.0.1  # Matches pyarrow version
  - jupyterlab=4.0.9
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0