name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.17.3,<1.25.0  # Ensures NumPy version compatibility
  - pyarrow=10.0.1
  - arrow-cpp=10.0.1
  - pandas
  - scikit-learn
  - pip
  - pip:
      - mlflow
      - wandb

